--
-- File generated with SQLiteStudio v3.4.17 on Thu Jul 30 09:47:48 2026
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: age_group
CREATE TABLE IF NOT EXISTS age_group (id PRIMARY KEY NOT NULL, name TEXT);
INSERT INTO age_group (id, name) VALUES (1, 'Girls Under15');
INSERT INTO age_group (id, name) VALUES (2, 'Boys Under15');
INSERT INTO age_group (id, name) VALUES (3, 'Girls under 16');
INSERT INTO age_group (id, name) VALUES (4, 'Boys under 16');
INSERT INTO age_group (id, name) VALUES (5, 'Girls under 17');
INSERT INTO age_group (id, name) VALUES (6, 'Boys Under 17');
INSERT INTO age_group (id, name) VALUES (7, 'Girls under 20');
INSERT INTO age_group (id, name) VALUES (8, 'Boys under 20');
INSERT INTO age_group (id, name) VALUES (9, 'Girls Under 14');
INSERT INTO age_group (id, name) VALUES (10, 'Boys Under 14');

-- Table: event
CREATE TABLE IF NOT EXISTS event (id PRIMARY KEY NOT NULL, name TEXT);
INSERT INTO event (id, name) VALUES (1, '100m');
INSERT INTO event (id, name) VALUES (2, '200m');
INSERT INTO event (id, name) VALUES (3, 'High jump');
INSERT INTO event (id, name) VALUES (4, 'Long jump');
INSERT INTO event (id, name) VALUES (5, 'Discus');
INSERT INTO event (id, name) VALUES (6, '400m');
INSERT INTO event (id, name) VALUES (7, '100m hurdles');
INSERT INTO event (id, name) VALUES (8, '80m hurdles');
INSERT INTO event (id, name) VALUES (9, '60m');
INSERT INTO event (id, name) VALUES (10, '3000m');
INSERT INTO event (id, name) VALUES (11, '1500m');
INSERT INTO event (id, name) VALUES (12, '800m');
INSERT INTO event (id, name) VALUES (13, '1600m walk');
INSERT INTO event (id, name) VALUES (14, '2000m steeple');
INSERT INTO event (id, name) VALUES (15, 'Shotput');
INSERT INTO event (id, name) VALUES (16, 'Javelin');
INSERT INTO event (id, name) VALUES (17, 'Triple jump');

-- Table: person
CREATE TABLE IF NOT EXISTS person (id PRIMARY KEY, name TEXT);
INSERT INTO person (id, name) VALUES (1, 'john kaisen');
INSERT INTO person (id, name) VALUES (2, 'patric baitmen');
INSERT INTO person (id, name) VALUES (3, 'Jamal muhamud');
INSERT INTO person (id, name) VALUES (4, 'olive yanter');
INSERT INTO person (id, name) VALUES (5, 'emma watson');
INSERT INTO person (id, name) VALUES (6, 'lucas blake');
INSERT INTO person (id, name) VALUES (7, 'chloe zane');
INSERT INTO person (id, name) VALUES (8, 'noah fence');
INSERT INTO person (id, name) VALUES (9, 'mia thermopolis');
INSERT INTO person (id, name) VALUES (10, 'ethan hunt');
INSERT INTO person (id, name) VALUES (11, 'sophia loren');
INSERT INTO person (id, name) VALUES (12, 'mason storm');
INSERT INTO person (id, name) VALUES (13, 'isabella swan');
INSERT INTO person (id, name) VALUES (14, 'liam neeson');
INSERT INTO person (id, name) VALUES (15, 'ava gardner');
INSERT INTO person (id, name) VALUES (16, 'william wallace');
INSERT INTO person (id, name) VALUES (17, 'harper lee');
INSERT INTO person (id, name) VALUES (18, 'james bond');
INSERT INTO person (id, name) VALUES (19, 'charlotte bronte');
INSERT INTO person (id, name) VALUES (20, 'benjamin button');
INSERT INTO person (id, name) VALUES (21, 'olivia pope');
INSERT INTO person (id, name) VALUES (22, 'fitzgerald grant');
INSERT INTO person (id, name) VALUES (23, 'mellie grant');
INSERT INTO person (id, name) VALUES (24, 'cyrus beene');
INSERT INTO person (id, name) VALUES (25, 'abby whelan');
INSERT INTO person (id, name) VALUES (26, 'huck finn');
INSERT INTO person (id, name) VALUES (27, 'quinn perkins');
INSERT INTO person (id, name) VALUES (28, 'david rosen');
INSERT INTO person (id, name) VALUES (29, 'jake ballard');
INSERT INTO person (id, name) VALUES (30, 'rowan pope');
INSERT INTO person (id, name) VALUES (31, 'meredith grey');
INSERT INTO person (id, name) VALUES (32, 'derek shepherd');
INSERT INTO person (id, name) VALUES (33, 'cristina yang');
INSERT INTO person (id, name) VALUES (34, 'alex karev');
INSERT INTO person (id, name) VALUES (35, 'izzie stevens');
INSERT INTO person (id, name) VALUES (36, 'george omalley');
INSERT INTO person (id, name) VALUES (37, 'miranda bailey');
INSERT INTO person (id, name) VALUES (38, 'richard webber');
INSERT INTO person (id, name) VALUES (39, 'callie torres');
INSERT INTO person (id, name) VALUES (40, 'arizona robbins');
INSERT INTO person (id, name) VALUES (41, 'owen hunt');
INSERT INTO person (id, name) VALUES (42, 'jackson avery');
INSERT INTO person (id, name) VALUES (43, 'april kepner');
INSERT INTO person (id, name) VALUES (44, 'lexie grey');
INSERT INTO person (id, name) VALUES (45, 'mark sloan');
INSERT INTO person (id, name) VALUES (46, 'amelia shepherd');
INSERT INTO person (id, name) VALUES (47, 'maggie pierce');
INSERT INTO person (id, name) VALUES (48, 'jo wilson');
INSERT INTO person (id, name) VALUES (49, 'stephanie edwards');
INSERT INTO person (id, name) VALUES (50, 'ben warren');
INSERT INTO person (id, name) VALUES (51, 'michael scott');
INSERT INTO person (id, name) VALUES (52, 'dwight schrute');
INSERT INTO person (id, name) VALUES (53, 'jim halpert');
INSERT INTO person (id, name) VALUES (54, 'pam beesly');
INSERT INTO person (id, name) VALUES (55, 'ryan howard');
INSERT INTO person (id, name) VALUES (56, 'andy bernard');
INSERT INTO person (id, name) VALUES (57, 'robert california');
INSERT INTO person (id, name) VALUES (58, 'stanley hudson');
INSERT INTO person (id, name) VALUES (59, 'kevin malone');
INSERT INTO person (id, name) VALUES (60, 'angela martin');
INSERT INTO person (id, name) VALUES (61, 'oscar martinez');
INSERT INTO person (id, name) VALUES (62, 'phyllis vance');
INSERT INTO person (id, name) VALUES (63, 'kelly kapoor');
INSERT INTO person (id, name) VALUES (64, 'toby flenderson');
INSERT INTO person (id, name) VALUES (65, 'creed bratton');
INSERT INTO person (id, name) VALUES (66, 'darryl philbin');
INSERT INTO person (id, name) VALUES (67, 'erin hannon');
INSERT INTO person (id, name) VALUES (68, 'gabe lewis');
INSERT INTO person (id, name) VALUES (69, 'holly flax');
INSERT INTO person (id, name) VALUES (70, 'jan levinson');
INSERT INTO person (id, name) VALUES (71, 'leslie knope');
INSERT INTO person (id, name) VALUES (72, 'ron swanson');
INSERT INTO person (id, name) VALUES (73, 'tom haverford');
INSERT INTO person (id, name) VALUES (74, 'ann perkins');
INSERT INTO person (id, name) VALUES (75, 'april ludgate');
INSERT INTO person (id, name) VALUES (76, 'andy dwyer');
INSERT INTO person (id, name) VALUES (77, 'ben wyatt');
INSERT INTO person (id, name) VALUES (78, 'chris traeger');
INSERT INTO person (id, name) VALUES (79, 'jerry gergich');
INSERT INTO person (id, name) VALUES (80, 'donna meagle');
INSERT INTO person (id, name) VALUES (81, 'jean ralphio');
INSERT INTO person (id, name) VALUES (82, 'craig middlebrooks');
INSERT INTO person (id, name) VALUES (83, 'tammy swanson');
INSERT INTO person (id, name) VALUES (84, 'lucy lawless');
INSERT INTO person (id, name) VALUES (85, 'burt macklin');
INSERT INTO person (id, name) VALUES (86, 'jake peralta');
INSERT INTO person (id, name) VALUES (87, 'rosa diaz');
INSERT INTO person (id, name) VALUES (88, 'terry jeffords');
INSERT INTO person (id, name) VALUES (89, 'amy santiago');
INSERT INTO person (id, name) VALUES (90, 'charles boyle');
INSERT INTO person (id, name) VALUES (91, 'raymond holt');
INSERT INTO person (id, name) VALUES (92, 'gina linetti');
INSERT INTO person (id, name) VALUES (93, 'hitchcock norm');
INSERT INTO person (id, name) VALUES (94, 'scully michael');
INSERT INTO person (id, name) VALUES (95, 'doug judy');
INSERT INTO person (id, name) VALUES (96, 'kevin cozner');
INSERT INTO person (id, name) VALUES (97, 'madeline wuntch');
INSERT INTO person (id, name) VALUES (98, 'pimento adrian');
INSERT INTO person (id, name) VALUES (99, 'teddy wells');
INSERT INTO person (id, name) VALUES (100, 'roger peralta');
INSERT INTO person (id, name) VALUES (101, 'luke skywalker');
INSERT INTO person (id, name) VALUES (102, 'leia organa');
INSERT INTO person (id, name) VALUES (103, 'han solo');
INSERT INTO person (id, name) VALUES (104, 'chewbacca');
INSERT INTO person (id, name) VALUES (105, 'darth vader');
INSERT INTO person (id, name) VALUES (106, 'obi wan');
INSERT INTO person (id, name) VALUES (107, 'yoda master');
INSERT INTO person (id, name) VALUES (108, 'boba fett');
INSERT INTO person (id, name) VALUES (109, 'lando calrissian');
INSERT INTO person (id, name) VALUES (110, 'padme amidala');
INSERT INTO person (id, name) VALUES (111, 'mace windu');
INSERT INTO person (id, name) VALUES (112, 'qui gon');
INSERT INTO person (id, name) VALUES (113, 'anakin skywalker');
INSERT INTO person (id, name) VALUES (114, 'rey palpatine');
INSERT INTO person (id, name) VALUES (115, 'finn trooper');
INSERT INTO person (id, name) VALUES (116, 'poe dameron');
INSERT INTO person (id, name) VALUES (117, 'kylo ren');
INSERT INTO person (id, name) VALUES (118, 'rose tico');
INSERT INTO person (id, name) VALUES (119, 'jabba hutt');
INSERT INTO person (id, name) VALUES (120, 'ahsoka tano');
INSERT INTO person (id, name) VALUES (121, 'harry potter');
INSERT INTO person (id, name) VALUES (122, 'hermione granger');
INSERT INTO person (id, name) VALUES (123, 'ron weasley');
INSERT INTO person (id, name) VALUES (124, 'draco malfoy');
INSERT INTO person (id, name) VALUES (125, 'albus dumbledore');
INSERT INTO person (id, name) VALUES (126, 'severus snape');
INSERT INTO person (id, name) VALUES (127, 'sirius black');
INSERT INTO person (id, name) VALUES (128, 'remus lupin');
INSERT INTO person (id, name) VALUES (129, 'rubeus hagrid');
INSERT INTO person (id, name) VALUES (130, 'minerva mcgonagall');
INSERT INTO person (id, name) VALUES (131, 'bellatrix lestrange');
INSERT INTO person (id, name) VALUES (132, 'voldemort tom');
INSERT INTO person (id, name) VALUES (133, 'neville longbottom');
INSERT INTO person (id, name) VALUES (134, 'luna lovegood');
INSERT INTO person (id, name) VALUES (135, 'ginny weasley');
INSERT INTO person (id, name) VALUES (136, 'fred weasley');
INSERT INTO person (id, name) VALUES (137, 'george weasley');
INSERT INTO person (id, name) VALUES (138, 'arthur weasley');
INSERT INTO person (id, name) VALUES (139, 'molly weasley');
INSERT INTO person (id, name) VALUES (140, 'lucius malfoy');
INSERT INTO person (id, name) VALUES (141, 'tony stark');
INSERT INTO person (id, name) VALUES (142, 'steve rogers');
INSERT INTO person (id, name) VALUES (143, 'bruce banner');
INSERT INTO person (id, name) VALUES (144, 'thor odinson');
INSERT INTO person (id, name) VALUES (145, 'natasha romanoff');
INSERT INTO person (id, name) VALUES (146, 'clint barton');
INSERT INTO person (id, name) VALUES (147, 'wanda maximoff');
INSERT INTO person (id, name) VALUES (148, 'vision bot');
INSERT INTO person (id, name) VALUES (149, 'sam wilson');
INSERT INTO person (id, name) VALUES (150, 'bucky barnes');
INSERT INTO person (id, name) VALUES (151, 'peter parker');
INSERT INTO person (id, name) VALUES (152, 'stephen strange');
INSERT INTO person (id, name) VALUES (153, 't challa');
INSERT INTO person (id, name) VALUES (154, 'carol danvers');
INSERT INTO person (id, name) VALUES (155, 'scott lang');
INSERT INTO person (id, name) VALUES (156, 'hope plym');
INSERT INTO person (id, name) VALUES (157, 'nick fury');
INSERT INTO person (id, name) VALUES (158, 'maria hill');
INSERT INTO person (id, name) VALUES (159, 'phil coulson');
INSERT INTO person (id, name) VALUES (160, 'peggy carter');
INSERT INTO person (id, name) VALUES (161, 'matt murdock');
INSERT INTO person (id, name) VALUES (162, 'jessica jones');
INSERT INTO person (id, name) VALUES (163, 'luke cage');
INSERT INTO person (id, name) VALUES (164, 'danny rand');
INSERT INTO person (id, name) VALUES (165, 'frank castle');
INSERT INTO person (id, name) VALUES (166, 'elektra natchios');
INSERT INTO person (id, name) VALUES (167, 'karen page');
INSERT INTO person (id, name) VALUES (168, 'foggy nelson');
INSERT INTO person (id, name) VALUES (169, 'claire temple');
INSERT INTO person (id, name) VALUES (170, 'wilson fisk');

-- Table: records
CREATE TABLE IF NOT EXISTS records (id PRIMARY KEY NOT NULL, event_id INTEGER REFERENCES event (id), age_group_id INTEGER REFERENCES age_group (id), person_id INTEGER REFERENCES person (id), year INTEGER, bhs_record NUMERIC);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (1, 1, 1, 1, 2019, 12);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (2, 1, 2, 2, 1987, 12.69);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (3, 1, 3, 3, 2020, 10.98);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (4, 2, 1, 1, 2019, 24);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (5, 2, 2, 2, 1987, 25.98);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (6, 2, 3, 3, 2020, 21.7);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (7, 3, 1, 1, 2020, '1.9m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (8, 3, 4, 4, 2024, '2.6m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (9, 3, 4, 4, 2023, 2.4);

-- View: Test 1
CREATE VIEW IF NOT EXISTS "Test 1" AS SELECT records.id, event.name FROM records INNER JOIN event ON records.event_id = event.id WHERE records.id == 2;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
