--
-- File generated with SQLiteStudio v3.4.17 on Tue Aug 4 12:30:03 2026
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: age_group
CREATE TABLE IF NOT EXISTS age_group (id PRIMARY KEY NOT NULL, name TEXT, Gender NUMERIC);
INSERT INTO age_group (id, name, Gender) VALUES (1, 'Girls Under 14', 1);
INSERT INTO age_group (id, name, Gender) VALUES (2, 'Boys Under 14', 2);
INSERT INTO age_group (id, name, Gender) VALUES (3, 'Girls under 15', 1);
INSERT INTO age_group (id, name, Gender) VALUES (4, 'Boys under 15', 2);
INSERT INTO age_group (id, name, Gender) VALUES (5, 'Girls under 16', 1);
INSERT INTO age_group (id, name, Gender) VALUES (6, 'Boys Under 16', 2);
INSERT INTO age_group (id, name, Gender) VALUES (7, 'Girls under 17', 1);
INSERT INTO age_group (id, name, Gender) VALUES (8, 'Boys under 17', 2);
INSERT INTO age_group (id, name, Gender) VALUES (9, 'Girls Under 20', 1);
INSERT INTO age_group (id, name, Gender) VALUES (10, 'Boys Under 20', 2);

-- Table: event
CREATE TABLE IF NOT EXISTS event (id PRIMARY KEY NOT NULL, name TEXT, Event_type NUMERIC);
INSERT INTO event (id, name, Event_type) VALUES (1, '100m', 1);
INSERT INTO event (id, name, Event_type) VALUES (2, '200m', 1);
INSERT INTO event (id, name, Event_type) VALUES (3, 'High jump', 2);
INSERT INTO event (id, name, Event_type) VALUES (4, 'Long jump', 2);
INSERT INTO event (id, name, Event_type) VALUES (5, 'Discus', 2);
INSERT INTO event (id, name, Event_type) VALUES (6, '400m', 1);
INSERT INTO event (id, name, Event_type) VALUES (7, '100m hurdles', 1);
INSERT INTO event (id, name, Event_type) VALUES (8, '80m hurdles', 1);
INSERT INTO event (id, name, Event_type) VALUES (9, '60m', 1);
INSERT INTO event (id, name, Event_type) VALUES (10, '3000m', 1);
INSERT INTO event (id, name, Event_type) VALUES (11, '1500m', 1);
INSERT INTO event (id, name, Event_type) VALUES (12, '800m', 1);
INSERT INTO event (id, name, Event_type) VALUES (13, '1600m walk', 1);
INSERT INTO event (id, name, Event_type) VALUES (14, '2000m steeple', 1);
INSERT INTO event (id, name, Event_type) VALUES (15, 'Shotput', 2);
INSERT INTO event (id, name, Event_type) VALUES (16, 'Javelin', 2);
INSERT INTO event (id, name, Event_type) VALUES (17, 'Triple jump', 2);

-- Table: person
CREATE TABLE IF NOT EXISTS person (id PRIMARY KEY, name TEXT);
INSERT INTO person (id, name) VALUES (1, 'john kaisen');
INSERT INTO person (id, name) VALUES (2, 'patric baitmen');
INSERT INTO person (id, name) VALUES (3, 'Jamal muhamud');
INSERT INTO person (id, name) VALUES (4, 'olive yanter');
INSERT INTO person (id, name) VALUES (5, 'emma watson');
INSERT INTO person (id, name) VALUES (6, 'lucas blake');
INSERT INTO person (id, name) VALUES (7, 'chloe zane');
INSERT INTO person (id, name) VALUES (8, 'noah fence');
INSERT INTO person (id, name) VALUES (9, 'mia thermopolis');
INSERT INTO person (id, name) VALUES (10, 'ethan hunt');
INSERT INTO person (id, name) VALUES (11, 'sophia loren');
INSERT INTO person (id, name) VALUES (12, 'mason storm');
INSERT INTO person (id, name) VALUES (13, 'isabella swan');
INSERT INTO person (id, name) VALUES (14, 'liam neeson');
INSERT INTO person (id, name) VALUES (15, 'ava gardner');
INSERT INTO person (id, name) VALUES (16, 'william wallace');
INSERT INTO person (id, name) VALUES (17, 'harper lee');
INSERT INTO person (id, name) VALUES (18, 'james bond');
INSERT INTO person (id, name) VALUES (19, 'charlotte bronte');
INSERT INTO person (id, name) VALUES (20, 'benjamin button');
INSERT INTO person (id, name) VALUES (21, 'olivia pope');
INSERT INTO person (id, name) VALUES (22, 'fitzgerald grant');
INSERT INTO person (id, name) VALUES (23, 'mellie grant');
INSERT INTO person (id, name) VALUES (24, 'cyrus beene');
INSERT INTO person (id, name) VALUES (25, 'abby whelan');
INSERT INTO person (id, name) VALUES (26, 'huck finn');
INSERT INTO person (id, name) VALUES (27, 'quinn perkins');
INSERT INTO person (id, name) VALUES (28, 'david rosen');
INSERT INTO person (id, name) VALUES (29, 'jake ballard');
INSERT INTO person (id, name) VALUES (30, 'rowan pope');
INSERT INTO person (id, name) VALUES (31, 'meredith grey');
INSERT INTO person (id, name) VALUES (32, 'derek shepherd');
INSERT INTO person (id, name) VALUES (33, 'cristina yang');
INSERT INTO person (id, name) VALUES (34, 'alex karev');
INSERT INTO person (id, name) VALUES (35, 'izzie stevens');
INSERT INTO person (id, name) VALUES (36, 'george omalley');
INSERT INTO person (id, name) VALUES (37, 'miranda bailey');
INSERT INTO person (id, name) VALUES (38, 'richard webber');
INSERT INTO person (id, name) VALUES (39, 'callie torres');
INSERT INTO person (id, name) VALUES (40, 'arizona robbins');
INSERT INTO person (id, name) VALUES (41, 'owen hunt');
INSERT INTO person (id, name) VALUES (42, 'jackson avery');
INSERT INTO person (id, name) VALUES (43, 'april kepner');
INSERT INTO person (id, name) VALUES (44, 'lexie grey');
INSERT INTO person (id, name) VALUES (45, 'mark sloan');
INSERT INTO person (id, name) VALUES (46, 'amelia shepherd');
INSERT INTO person (id, name) VALUES (47, 'maggie pierce');
INSERT INTO person (id, name) VALUES (48, 'jo wilson');
INSERT INTO person (id, name) VALUES (49, 'stephanie edwards');
INSERT INTO person (id, name) VALUES (50, 'ben warren');
INSERT INTO person (id, name) VALUES (51, 'michael scott');
INSERT INTO person (id, name) VALUES (52, 'dwight schrute');
INSERT INTO person (id, name) VALUES (53, 'jim halpert');
INSERT INTO person (id, name) VALUES (54, 'pam beesly');
INSERT INTO person (id, name) VALUES (55, 'ryan howard');
INSERT INTO person (id, name) VALUES (56, 'andy bernard');
INSERT INTO person (id, name) VALUES (57, 'robert california');
INSERT INTO person (id, name) VALUES (58, 'stanley hudson');
INSERT INTO person (id, name) VALUES (59, 'kevin malone');
INSERT INTO person (id, name) VALUES (60, 'angela martin');
INSERT INTO person (id, name) VALUES (61, 'oscar martinez');
INSERT INTO person (id, name) VALUES (62, 'phyllis vance');
INSERT INTO person (id, name) VALUES (63, 'kelly kapoor');
INSERT INTO person (id, name) VALUES (64, 'toby flenderson');
INSERT INTO person (id, name) VALUES (65, 'creed bratton');
INSERT INTO person (id, name) VALUES (66, 'darryl philbin');
INSERT INTO person (id, name) VALUES (67, 'erin hannon');
INSERT INTO person (id, name) VALUES (68, 'gabe lewis');
INSERT INTO person (id, name) VALUES (69, 'holly flax');
INSERT INTO person (id, name) VALUES (70, 'jan levinson');
INSERT INTO person (id, name) VALUES (71, 'leslie knope');
INSERT INTO person (id, name) VALUES (72, 'ron swanson');
INSERT INTO person (id, name) VALUES (73, 'tom haverford');
INSERT INTO person (id, name) VALUES (74, 'ann perkins');
INSERT INTO person (id, name) VALUES (75, 'april ludgate');
INSERT INTO person (id, name) VALUES (76, 'andy dwyer');
INSERT INTO person (id, name) VALUES (77, 'ben wyatt');
INSERT INTO person (id, name) VALUES (78, 'chris traeger');
INSERT INTO person (id, name) VALUES (79, 'jerry gergich');
INSERT INTO person (id, name) VALUES (80, 'donna meagle');
INSERT INTO person (id, name) VALUES (81, 'jean ralphio');
INSERT INTO person (id, name) VALUES (82, 'craig middlebrooks');
INSERT INTO person (id, name) VALUES (83, 'tammy swanson');
INSERT INTO person (id, name) VALUES (84, 'lucy lawless');
INSERT INTO person (id, name) VALUES (85, 'burt macklin');
INSERT INTO person (id, name) VALUES (86, 'jake peralta');
INSERT INTO person (id, name) VALUES (87, 'rosa diaz');
INSERT INTO person (id, name) VALUES (88, 'terry jeffords');
INSERT INTO person (id, name) VALUES (89, 'amy santiago');
INSERT INTO person (id, name) VALUES (90, 'charles boyle');
INSERT INTO person (id, name) VALUES (91, 'raymond holt');
INSERT INTO person (id, name) VALUES (92, 'gina linetti');
INSERT INTO person (id, name) VALUES (93, 'hitchcock norm');
INSERT INTO person (id, name) VALUES (94, 'scully michael');
INSERT INTO person (id, name) VALUES (95, 'doug judy');
INSERT INTO person (id, name) VALUES (96, 'kevin cozner');
INSERT INTO person (id, name) VALUES (97, 'madeline wuntch');
INSERT INTO person (id, name) VALUES (98, 'pimento adrian');
INSERT INTO person (id, name) VALUES (99, 'teddy wells');
INSERT INTO person (id, name) VALUES (100, 'roger peralta');
INSERT INTO person (id, name) VALUES (101, 'luke skywalker');
INSERT INTO person (id, name) VALUES (102, 'leia organa');
INSERT INTO person (id, name) VALUES (103, 'han solo');
INSERT INTO person (id, name) VALUES (104, 'chewbacca');
INSERT INTO person (id, name) VALUES (105, 'darth vader');
INSERT INTO person (id, name) VALUES (106, 'obi wan');
INSERT INTO person (id, name) VALUES (107, 'yoda master');
INSERT INTO person (id, name) VALUES (108, 'boba fett');
INSERT INTO person (id, name) VALUES (109, 'lando calrissian');
INSERT INTO person (id, name) VALUES (110, 'padme amidala');
INSERT INTO person (id, name) VALUES (111, 'mace windu');
INSERT INTO person (id, name) VALUES (112, 'qui gon');
INSERT INTO person (id, name) VALUES (113, 'anakin skywalker');
INSERT INTO person (id, name) VALUES (114, 'rey palpatine');
INSERT INTO person (id, name) VALUES (115, 'finn trooper');
INSERT INTO person (id, name) VALUES (116, 'poe dameron');
INSERT INTO person (id, name) VALUES (117, 'kylo ren');
INSERT INTO person (id, name) VALUES (118, 'rose tico');
INSERT INTO person (id, name) VALUES (119, 'jabba hutt');
INSERT INTO person (id, name) VALUES (120, 'ahsoka tano');
INSERT INTO person (id, name) VALUES (121, 'harry potter');
INSERT INTO person (id, name) VALUES (122, 'hermione granger');
INSERT INTO person (id, name) VALUES (123, 'ron weasley');
INSERT INTO person (id, name) VALUES (124, 'draco malfoy');
INSERT INTO person (id, name) VALUES (125, 'albus dumbledore');
INSERT INTO person (id, name) VALUES (126, 'severus snape');
INSERT INTO person (id, name) VALUES (127, 'sirius black');
INSERT INTO person (id, name) VALUES (128, 'remus lupin');
INSERT INTO person (id, name) VALUES (129, 'rubeus hagrid');
INSERT INTO person (id, name) VALUES (130, 'minerva mcgonagall');
INSERT INTO person (id, name) VALUES (131, 'bellatrix lestrange');
INSERT INTO person (id, name) VALUES (132, 'voldemort tom');
INSERT INTO person (id, name) VALUES (133, 'neville longbottom');
INSERT INTO person (id, name) VALUES (134, 'luna lovegood');
INSERT INTO person (id, name) VALUES (135, 'ginny weasley');
INSERT INTO person (id, name) VALUES (136, 'fred weasley');
INSERT INTO person (id, name) VALUES (137, 'george weasley');
INSERT INTO person (id, name) VALUES (138, 'arthur weasley');
INSERT INTO person (id, name) VALUES (139, 'molly weasley');
INSERT INTO person (id, name) VALUES (140, 'lucius malfoy');
INSERT INTO person (id, name) VALUES (141, 'tony stark');
INSERT INTO person (id, name) VALUES (142, 'steve rogers');
INSERT INTO person (id, name) VALUES (143, 'bruce banner');
INSERT INTO person (id, name) VALUES (144, 'thor odinson');
INSERT INTO person (id, name) VALUES (145, 'natasha romanoff');
INSERT INTO person (id, name) VALUES (146, 'clint barton');
INSERT INTO person (id, name) VALUES (147, 'wanda maximoff');
INSERT INTO person (id, name) VALUES (148, 'vision bot');
INSERT INTO person (id, name) VALUES (149, 'sam wilson');
INSERT INTO person (id, name) VALUES (150, 'bucky barnes');
INSERT INTO person (id, name) VALUES (151, 'peter parker');
INSERT INTO person (id, name) VALUES (152, 'stephen strange');
INSERT INTO person (id, name) VALUES (153, 't challa');
INSERT INTO person (id, name) VALUES (154, 'carol danvers');
INSERT INTO person (id, name) VALUES (155, 'scott lang');
INSERT INTO person (id, name) VALUES (156, 'hope plym');
INSERT INTO person (id, name) VALUES (157, 'nick fury');
INSERT INTO person (id, name) VALUES (158, 'maria hill');
INSERT INTO person (id, name) VALUES (159, 'phil coulson');
INSERT INTO person (id, name) VALUES (160, 'peggy carter');
INSERT INTO person (id, name) VALUES (161, 'matt murdock');
INSERT INTO person (id, name) VALUES (162, 'jessica jones');
INSERT INTO person (id, name) VALUES (163, 'luke cage');
INSERT INTO person (id, name) VALUES (164, 'danny rand');
INSERT INTO person (id, name) VALUES (165, 'frank castle');
INSERT INTO person (id, name) VALUES (166, 'elektra natchios');
INSERT INTO person (id, name) VALUES (167, 'karen page');
INSERT INTO person (id, name) VALUES (168, 'foggy nelson');
INSERT INTO person (id, name) VALUES (169, 'claire temple');
INSERT INTO person (id, name) VALUES (170, 'wilson fisk');
INSERT INTO person (id, name) VALUES (171, 'baraby tod');

-- Table: records
CREATE TABLE IF NOT EXISTS records (id PRIMARY KEY NOT NULL, event_id INTEGER REFERENCES event (id), age_group_id INTEGER REFERENCES age_group (id), person_id INTEGER REFERENCES person (id), year INTEGER, bhs_record NUMERIC);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (1, 1, 1, 1, 2021, 12.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (2, 1, 2, 2, 2022, 11.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (3, 1, 3, 3, 2020, 12.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (4, 1, 4, 4, 2023, 11.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (5, 1, 5, 5, 2019, 12.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (6, 1, 6, 6, 2024, 11.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (7, 1, 7, 7, 2018, 11.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (8, 1, 8, 8, 2021, 10.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (9, 1, 9, 9, 2023, 13.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (10, 1, 10, 10, 2023, 12.4);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (11, 2, 1, 11, 2021, 26.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (12, 2, 2, 12, 2020, 24.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (13, 2, 3, 13, 2019, 25.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (14, 2, 4, 14, 2022, 23.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (15, 2, 5, 15, 2023, 25.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (16, 2, 6, 16, 2021, 22.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (17, 2, 7, 17, 2024, 24.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (18, 2, 8, 18, 2018, 21.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (19, 2, 9, 19, 2022, 27.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (20, 2, 10, 20, 2022, 26.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (21, 3, 1, 21, 2019, '1.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (22, 3, 2, 22, 2023, '1.6m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (23, 3, 3, 23, 2021, '1.65m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (24, 3, 4, 24, 2022, '1.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (25, 3, 5, 25, 2020, '1.7m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (26, 3, 6, 26, 2018, '1.95m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (27, 3, 7, 27, 2024, '1.75m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (28, 3, 8, 28, 2019, '2.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (29, 3, 9, 29, 2023, '1.4m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (30, 3, 10, 30, 2023, '1.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (31, 4, 1, 31, 2020, '4.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (32, 4, 2, 32, 2021, '5.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (33, 4, 3, 33, 2019, '5.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (34, 4, 4, 34, 2023, '5.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (35, 4, 5, 35, 2022, '5.4m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (36, 4, 6, 36, 2018, '6.3m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (37, 4, 7, 37, 2024, '5.7m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (38, 4, 8, 38, 2021, '6.9m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (39, 4, 9, 39, 2022, '4.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (40, 4, 10, 40, 2022, '4.9m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (41, 5, 1, 41, 2018, '28.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (42, 5, 2, 42, 2022, '35.0m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (43, 5, 3, 43, 2021, '32.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (44, 5, 4, 44, 2020, '40.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (45, 5, 5, 45, 2024, '36.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (46, 5, 6, 46, 2019, '45.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (47, 5, 7, 47, 2023, '40.0m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (48, 5, 8, 48, 2021, '52.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (49, 5, 9, 49, 2020, '24.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (50, 5, 10, 50, 2020, '30.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (51, 6, 1, 51, 2021, 62.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (52, 6, 2, 52, 2019, 58.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (53, 6, 3, 53, 2023, 60.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (54, 6, 4, 54, 2022, 54.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (55, 6, 5, 55, 2020, 58);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (56, 6, 6, 56, 2024, 51.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (57, 6, 7, 57, 2018, 56.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (58, 6, 8, 58, 2021, 49.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (59, 6, 9, 59, 2022, 65.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (60, 6, 10, 60, 2022, 61.4);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (61, 7, 1, 61, 2019, 16.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (62, 7, 2, 62, 2023, 15.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (63, 7, 3, 63, 2020, 15.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (64, 7, 4, 64, 2018, 14.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (65, 7, 5, 65, 2022, 15.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (66, 7, 6, 66, 2021, 13.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (67, 7, 7, 67, 2024, 14.6);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (68, 7, 8, 68, 2019, 13.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (69, 7, 9, 69, 2023, 17.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (70, 7, 10, 70, 2023, 16.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (71, 8, 1, 71, 2022, 13.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (72, 8, 2, 72, 2020, 12.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (73, 8, 3, 73, 2024, 12.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (74, 8, 4, 74, 2021, 11.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (75, 8, 5, 75, 2019, 12.3);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (76, 8, 6, 76, 2018, 11);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (77, 8, 7, 77, 2023, 11.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (78, 8, 8, 78, 2022, 10.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (79, 8, 9, 79, 2020, 14.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (80, 8, 10, 80, 2020, 13.1);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (81, 9, 1, 81, 2024, 8.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (82, 9, 2, 82, 2021, 7.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (83, 9, 3, 83, 2022, 8.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (84, 9, 4, 84, 2020, 7.5);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (85, 9, 5, 85, 2018, 8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (86, 9, 6, 86, 2019, 7.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (87, 9, 7, 87, 2023, 7.8);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (88, 9, 8, 88, 2024, 6.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (89, 9, 9, 89, 2021, 8.9);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (90, 9, 10, 90, 2021, 8.2);
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (91, 10, 1, 91, 2020, '11:15.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (92, 10, 2, 92, 2022, '10:30.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (93, 10, 3, 93, 2021, '10:50.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (94, 10, 4, 94, 2019, '9:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (95, 10, 5, 95, 2023, '10:25.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (96, 10, 6, 96, 2024, '9:15.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (97, 10, 7, 97, 2018, '10:05.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (98, 10, 8, 98, 2023, '8:50.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (99, 10, 9, 99, 2022, '11:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (100, 10, 10, 100, 2022, '11:00.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (101, 11, 1, 101, 2023, '5:20.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (102, 11, 2, 102, 2019, '4:50.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (103, 11, 3, 103, 2024, '5:05.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (104, 11, 4, 104, 2020, '4:30.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (105, 11, 5, 105, 2021, '4:55.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (106, 11, 6, 106, 2022, '4:10.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (107, 11, 7, 107, 2018, '4:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (108, 11, 8, 108, 2024, '3:55.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (109, 11, 9, 109, 2019, '5:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (110, 11, 10, 110, 2019, '5:15.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (111, 12, 1, 111, 2018, '2:35.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (112, 12, 2, 112, 2024, '2:20.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (113, 12, 3, 113, 2020, '2:28.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (114, 12, 4, 114, 2021, '2:10.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (115, 12, 5, 115, 2019, '2:22.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (116, 12, 6, 116, 2023, '2:02.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (117, 12, 7, 117, 2022, '2:18.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (118, 12, 8, 118, 2018, '1:54.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (119, 12, 9, 119, 2024, '2:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (120, 12, 10, 120, 2024, '2:30.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (121, 13, 1, 121, 2021, '8:15.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (122, 13, 2, 122, 2020, '7:50.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (123, 13, 3, 123, 2023, '8:00.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (124, 13, 4, 124, 2019, '7:20.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (125, 13, 5, 125, 2024, '7:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (126, 13, 6, 126, 2022, '7:00.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (127, 13, 7, 127, 2018, '7:35.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (128, 13, 8, 128, 2021, '6:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (129, 13, 9, 129, 2020, '8:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (130, 13, 10, 130, 2020, '8:10.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (131, 14, 1, 131, 2019, '8:20.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (132, 14, 2, 132, 2021, '7:45.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (133, 14, 3, 133, 2022, '8:05.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (134, 14, 4, 134, 2023, '7:15.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (135, 14, 5, 135, 2020, '7:50.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (136, 14, 6, 136, 2018, '6:55.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (137, 14, 7, 137, 2024, '7:30.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (138, 14, 8, 138, 2019, '6:35.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (139, 14, 9, 139, 2021, '8:50.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (140, 14, 10, 140, 2021, '8:15.0');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (141, 15, 1, 141, 2024, '9.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (142, 15, 2, 142, 2022, '11.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (143, 15, 3, 143, 2019, '10.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (144, 15, 4, 144, 2021, '13.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (145, 15, 5, 145, 2018, '11.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (146, 15, 6, 146, 2020, '15.0m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (147, 15, 7, 147, 2023, '12.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (148, 15, 8, 148, 2024, '16.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (149, 15, 9, 149, 2022, '8.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (150, 15, 10, 150, 2022, '9.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (151, 16, 1, 151, 2023, '28.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (152, 16, 2, 152, 2020, '35.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (153, 16, 3, 153, 2018, '32.4m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (154, 16, 4, 154, 2024, '42.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (155, 16, 5, 155, 2019, '36.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (156, 16, 6, 156, 2021, '50.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (157, 16, 7, 157, 2022, '40.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (158, 16, 8, 158, 2023, '58.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (159, 16, 9, 159, 2020, '22.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (160, 16, 10, 160, 2020, '30.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (161, 17, 1, 161, 2022, '9.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (162, 17, 2, 162, 2021, '10.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (163, 17, 3, 163, 2024, '10.2m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (164, 17, 4, 164, 2018, '12.1m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (165, 17, 5, 165, 2020, '11.0m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (166, 17, 6, 166, 2019, '13.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (167, 17, 7, 167, 2023, '11.8m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (168, 17, 8, 168, 2022, '14.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (169, 17, 9, 169, 2021, '8.5m');
INSERT INTO records (id, event_id, age_group_id, person_id, year, bhs_record) VALUES (170, 17, 10, 170, 2021, '9.8m');

-- View: Test 1
CREATE VIEW IF NOT EXISTS "Test 1" AS SELECT records.id, event.name FROM records INNER JOIN event ON records.event_id = event.id WHERE records.id == 2;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
